typography_spectrum: 0.19555379217490554
color:
  brandColors:
    - '#b10000'
    - '#ffffff'
    - '#c1c1c1'
    - '#2e2e2e'
    - '#ab4040'
  brandStrength: 0.7470392233226448
  lightness: 0.9061826774850488
  saturation: 0.5174335921183228
  rhythmicContrast: 0.43173233699053526
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: dosa
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
